CREATE TABLE "incription_pupitre" (
                                      "id_fanfaron" TEXT NOT NULL UNIQUE,
                                      "id_pupitre" INTEGER NOT NULL UNIQUE,
                                      PRIMARY KEY("id_fanfaron", "id_pupitre")
);

CREATE TABLE "fanfaron" (
                            "login" TEXT NOT NULL UNIQUE,
                            "nom" TEXT,
                            "prenom" TEXT,
                            "adresse" TEXT,
                            "genre" TEXT,
                            "mdp" TEXT,
                            "crt_alimentaire" TEXT,
                            "derniere_connection" TIMESTAMP,
                            "date_creation" TIMESTAMP,
                            PRIMARY KEY("login")
);

CREATE TABLE "evenement" (
                             "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                             "date" TIMESTAMP,
                             "nom" TEXT,
                             "lieu" TEXT,
                             "description" TEXT,
                             "type" TEXT,
                             "createur" TEXT,
                             PRIMARY KEY("id")
);

CREATE TABLE "groupe" (
                          "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                          "nom" TEXT,
                          PRIMARY KEY("id")
);

CREATE TABLE "pupitre" (
                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                           "nom" TEXT,
                           PRIMARY KEY("id")
);

CREATE TABLE "incription_groupe" (
                                     "id_fanfaron" TEXT NOT NULL UNIQUE,
                                     "id_groupe" INTEGER NOT NULL UNIQUE,
                                     PRIMARY KEY("id_fanfaron", "id_groupe")
);

CREATE TABLE "inscription_evenement" (
                                         "id_fanfaron" TEXT NOT NULL UNIQUE,
                                         "id_pupitre" INTEGER NOT NULL,
                                         "id_evenement" INTEGER NOT NULL,
                                         "status" TEXT,
                                         PRIMARY KEY("id_fanfaron", "id_pupitre", "id_evenement")
);

ALTER TABLE "evenement"
ADD CONSTRAINT unique_createur UNIQUE ("createur");

ALTER TABLE "fanfaron"
    ADD FOREIGN KEY("login") REFERENCES "incription_groupe"("id_fanfaron")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "groupe"
    ADD FOREIGN KEY("id") REFERENCES "incription_groupe"("id_groupe")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "fanfaron"
    ADD FOREIGN KEY("login") REFERENCES "incription_pupitre"("id_fanfaron")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "incription_pupitre"
    ADD FOREIGN KEY("id_pupitre") REFERENCES "pupitre"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inscription_evenement"
    ADD FOREIGN KEY("id_fanfaron") REFERENCES "fanfaron"("login")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inscription_evenement"
    ADD FOREIGN KEY("id_pupitre") REFERENCES "pupitre"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "inscription_evenement"
    ADD FOREIGN KEY("id_evenement") REFERENCES "evenement"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;