CREATE TABLE "fanfaron" (
                            "login" TEXT NOT NULL UNIQUE,
                            "nom" TEXT,
                            "prenom" TEXT,
                            "adresse" TEXT,
                            "genre" TEXT,
                            "mdp" BYTEA NOT NULL ,
                            "crt_alimentaire" TEXT,
                            "derniere_connection" TIMESTAMP,
                            "date_creation" TIMESTAMP,
                            is_Admin BOOLEAN,
                            activated BOOLEAN,
                            PRIMARY KEY("login")
);

CREATE TABLE "evenement" (
                             "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                             "date" TIMESTAMP,
                             "nom" TEXT,
                             "lieu" TEXT,
                             "description" TEXT,
                             "duree" INTEGER,
                             "createur" TEXT NOT NULL,
                             PRIMARY KEY("id"),
                             FOREIGN KEY("createur") REFERENCES "fanfaron"("login") ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE "groupe" (
                          "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                          "nom" TEXT,
                          PRIMARY KEY("id")
);

CREATE TABLE "pupitre" (
                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                           "nom" TEXT,
                           PRIMARY KEY("id")
);

CREATE TABLE "inscription_pupitre" (
                                      "id_fanfaron" TEXT NOT NULL,
                                      "id_pupitre" INTEGER NOT NULL,
                                      PRIMARY KEY("id_fanfaron", "id_pupitre"),
                                      FOREIGN KEY("id_fanfaron") REFERENCES "fanfaron"("login") ON UPDATE CASCADE ON DELETE CASCADE,
                                      FOREIGN KEY("id_pupitre") REFERENCES "pupitre"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "inscription_groupe" (
                                     "id_fanfaron" TEXT NOT NULL,
                                     "id_groupe" INTEGER NOT NULL,
                                     PRIMARY KEY("id_fanfaron", "id_groupe"),
                                     FOREIGN KEY("id_fanfaron") REFERENCES "fanfaron"("login") ON UPDATE CASCADE ON DELETE CASCADE,
                                     FOREIGN KEY("id_groupe") REFERENCES "groupe"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "inscription_evenement" (
                                         "id_fanfaron" TEXT NOT NULL,
                                         "id_pupitre" INTEGER NOT NULL,
                                         "id_evenement" INTEGER NOT NULL,
                                         "status" TEXT,
                                         PRIMARY KEY("id_fanfaron", "id_pupitre", "id_evenement"),
                                         FOREIGN KEY("id_fanfaron") REFERENCES "fanfaron"("login") ON UPDATE CASCADE ON DELETE CASCADE,
                                         FOREIGN KEY("id_pupitre") REFERENCES "pupitre"("id") ON UPDATE CASCADE ON DELETE CASCADE,
                                         FOREIGN KEY("id_evenement") REFERENCES "evenement"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO fanfaron_user;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO groupe (nom)
VALUES
    ('Commission prestation'),
    ('Commission artistique'),
    ('Commission logistique'),
    ('Commission communication interne');

INSERT INTO pupitre (nom)
VALUES
    ('Clarinette'),
    ('Saxophone alto'),
    ('Euphonium'),
    ('Percussion'),
    ('Basse'),
    ('Trompette'),
    ('Saxophone baryton'),
    ('Trombone');

INSERT INTO fanfaron (
    login, nom, prenom, adresse, genre, mdp, crt_alimentaire,
    derniere_connection, date_creation, is_Admin, activated
)
VALUES (
           'admin', 'admin', 'admin', 'admin@admin.fr', 'Autre',
           digest('admin123', 'sha256'),
           'Aucun', NOW(), NOW(), TRUE, TRUE
       );

